import type {
	EtcdKey,
	EtcdClusterInfo,
	EtcdAuthStatus,
	EtcdUser,
	EtcdRole,
	EtcdLease,
	EtcdAlarm,
	EtcdMember,
	EtcdEndpointHealth,
	EtcdEndpointStatus,
} from "../types/etcd";

export const mockKeys: Record<string, EtcdKey[]> = {
	"/": [
		{
			key: "leader",
			isDirectory: false,
			revision: 500,
			createRevision: 1,
			modRevision: 500,
		},
		{
			key: "cluster-id",
			isDirectory: false,
			revision: 1,
			createRevision: 1,
			modRevision: 1,
		},
		{
			key: "version",
			isDirectory: false,
			revision: 10,
			createRevision: 1,
			modRevision: 10,
		},
		{ key: "config/", isDirectory: true },
		{ key: "services/", isDirectory: true },
		{ key: "clusters/", isDirectory: true },
		{ key: "users/", isDirectory: true },
		{ key: "jobs/", isDirectory: true },
		{ key: "locks/", isDirectory: true },
		{ key: "elections/", isDirectory: true },
		{ key: "discovery/", isDirectory: true },
	],
	"config/": [
		{
			key: "database",
			isDirectory: false,
			revision: 15,
			createRevision: 1,
			modRevision: 15,
		},
		{
			key: "redis",
			isDirectory: false,
			revision: 8,
			createRevision: 2,
			modRevision: 8,
		},
		{
			key: "kafka",
			isDirectory: false,
			revision: 45,
			createRevision: 3,
			modRevision: 45,
		},
		{
			key: "elasticsearch",
			isDirectory: false,
			revision: 22,
			createRevision: 4,
			modRevision: 22,
		},
		{ key: "app/", isDirectory: true },
		{ key: "logging/", isDirectory: true },
		{ key: "security/", isDirectory: true },
	],
	"config/app/": [
		{
			key: "settings",
			isDirectory: false,
			revision: 42,
			createRevision: 5,
			modRevision: 42,
		},
		{
			key: "features",
			isDirectory: false,
			revision: 23,
			createRevision: 6,
			modRevision: 23,
		},
		{
			key: "limits",
			isDirectory: false,
			revision: 18,
			createRevision: 7,
			modRevision: 18,
		},
		{
			key: "cache-ttl",
			isDirectory: false,
			revision: 9,
			createRevision: 8,
			modRevision: 9,
		},
	],
	"config/logging/": [
		{
			key: "level",
			isDirectory: false,
			revision: 12,
			createRevision: 10,
			modRevision: 12,
		},
		{
			key: "format",
			isDirectory: false,
			revision: 5,
			createRevision: 11,
			modRevision: 5,
		},
		{
			key: "outputs",
			isDirectory: false,
			revision: 8,
			createRevision: 12,
			modRevision: 8,
		},
	],
	"config/security/": [
		{
			key: "tls-config",
			isDirectory: false,
			revision: 30,
			createRevision: 15,
			modRevision: 30,
		},
		{
			key: "cors-policy",
			isDirectory: false,
			revision: 14,
			createRevision: 16,
			modRevision: 14,
		},
		{
			key: "rate-limits",
			isDirectory: false,
			revision: 25,
			createRevision: 17,
			modRevision: 25,
		},
	],
	"services/": [
		{
			key: "api-gateway",
			isDirectory: false,
			revision: 100,
			createRevision: 10,
			modRevision: 100,
		},
		{
			key: "auth-service",
			isDirectory: false,
			revision: 67,
			createRevision: 11,
			modRevision: 67,
		},
		{
			key: "user-service",
			isDirectory: false,
			revision: 89,
			createRevision: 12,
			modRevision: 89,
		},
		{
			key: "order-service",
			isDirectory: false,
			revision: 156,
			createRevision: 13,
			modRevision: 156,
		},
		{
			key: "inventory-service",
			isDirectory: false,
			revision: 78,
			createRevision: 14,
			modRevision: 78,
		},
		{
			key: "notification-service",
			isDirectory: false,
			revision: 45,
			createRevision: 15,
			modRevision: 45,
		},
		{
			key: "billing-service",
			isDirectory: false,
			revision: 92,
			createRevision: 16,
			modRevision: 92,
		},
		{
			key: "analytics-service",
			isDirectory: false,
			revision: 134,
			createRevision: 17,
			modRevision: 134,
		},
		{
			key: "search-service",
			isDirectory: false,
			revision: 77,
			createRevision: 18,
			modRevision: 77,
		},
		{
			key: "cache-service",
			isDirectory: false,
			revision: 65,
			createRevision: 19,
			modRevision: 65,
		},
		{
			key: "logging-service",
			isDirectory: false,
			revision: 112,
			createRevision: 20,
			modRevision: 112,
		},
		{
			key: "metrics-service",
			isDirectory: false,
			revision: 88,
			createRevision: 21,
			modRevision: 88,
		},
		{
			key: "config-service",
			isDirectory: false,
			revision: 54,
			createRevision: 22,
			modRevision: 54,
		},
		{
			key: "gateway-service",
			isDirectory: false,
			revision: 143,
			createRevision: 23,
			modRevision: 143,
		},
		{
			key: "queue-service",
			isDirectory: false,
			revision: 98,
			createRevision: 24,
			modRevision: 98,
		},
		{
			key: "scheduler-service",
			isDirectory: false,
			revision: 76,
			createRevision: 25,
			modRevision: 76,
		},
		{
			key: "worker-service",
			isDirectory: false,
			revision: 167,
			createRevision: 26,
			modRevision: 167,
		},
		{
			key: "monitor-service",
			isDirectory: false,
			revision: 59,
			createRevision: 27,
			modRevision: 59,
		},
		{
			key: "backup-service",
			isDirectory: false,
			revision: 123,
			createRevision: 28,
			modRevision: 123,
		},
		{
			key: "restore-service",
			isDirectory: false,
			revision: 87,
			createRevision: 29,
			modRevision: 87,
		},
		{
			key: "audit-service",
			isDirectory: false,
			revision: 145,
			createRevision: 30,
			modRevision: 145,
		},
		{
			key: "compliance-service",
			isDirectory: false,
			revision: 72,
			createRevision: 31,
			modRevision: 72,
		},
		{
			key: "security-service",
			isDirectory: false,
			revision: 189,
			createRevision: 32,
			modRevision: 189,
		},
		{
			key: "identity-service",
			isDirectory: false,
			revision: 156,
			createRevision: 33,
			modRevision: 156,
		},
		{
			key: "access-service",
			isDirectory: false,
			revision: 94,
			createRevision: 34,
			modRevision: 94,
		},
		{
			key: "policy-service",
			isDirectory: false,
			revision: 81,
			createRevision: 35,
			modRevision: 81,
		},
		{
			key: "event-service",
			isDirectory: false,
			revision: 203,
			createRevision: 36,
			modRevision: 203,
		},
		{
			key: "stream-service",
			isDirectory: false,
			revision: 117,
			createRevision: 37,
			modRevision: 117,
		},
		{
			key: "transform-service",
			isDirectory: false,
			revision: 69,
			createRevision: 38,
			modRevision: 69,
		},
		{
			key: "validate-service",
			isDirectory: false,
			revision: 142,
			createRevision: 39,
			modRevision: 142,
		},
		{ key: "payment/", isDirectory: true },
		{ key: "messaging/", isDirectory: true },
	],
	"services/payment/": [
		{
			key: "stripe",
			isDirectory: false,
			revision: 34,
			createRevision: 20,
			modRevision: 34,
		},
		{
			key: "paypal",
			isDirectory: false,
			revision: 12,
			createRevision: 21,
			modRevision: 12,
		},
		{
			key: "braintree",
			isDirectory: false,
			revision: 8,
			createRevision: 22,
			modRevision: 8,
		},
	],
	"services/messaging/": [
		{
			key: "email",
			isDirectory: false,
			revision: 56,
			createRevision: 25,
			modRevision: 56,
		},
		{
			key: "sms",
			isDirectory: false,
			revision: 23,
			createRevision: 26,
			modRevision: 23,
		},
		{
			key: "push",
			isDirectory: false,
			revision: 41,
			createRevision: 27,
			modRevision: 41,
		},
	],
	"clusters/": [
		{ key: "prod/", isDirectory: true },
		{ key: "staging/", isDirectory: true },
		{ key: "dev/", isDirectory: true },
	],
	"clusters/prod/": [
		{
			key: "node1",
			isDirectory: false,
			revision: 200,
			createRevision: 30,
			modRevision: 200,
		},
		{
			key: "node2",
			isDirectory: false,
			revision: 198,
			createRevision: 31,
			modRevision: 198,
		},
		{
			key: "node3",
			isDirectory: false,
			revision: 195,
			createRevision: 32,
			modRevision: 195,
		},
		{
			key: "node4",
			isDirectory: false,
			revision: 190,
			createRevision: 33,
			modRevision: 190,
		},
		{
			key: "node5",
			isDirectory: false,
			revision: 188,
			createRevision: 34,
			modRevision: 188,
		},
	],
	"clusters/staging/": [
		{
			key: "node1",
			isDirectory: false,
			revision: 150,
			createRevision: 40,
			modRevision: 150,
		},
		{
			key: "node2",
			isDirectory: false,
			revision: 148,
			createRevision: 41,
			modRevision: 148,
		},
	],
	"clusters/dev/": [
		{
			key: "local",
			isDirectory: false,
			revision: 50,
			createRevision: 50,
			modRevision: 50,
		},
	],
	"users/": [
		{
			key: "admin",
			isDirectory: false,
			revision: 5,
			createRevision: 1,
			modRevision: 5,
		},
		{
			key: "readonly",
			isDirectory: false,
			revision: 3,
			createRevision: 2,
			modRevision: 3,
		},
		{
			key: "service-account-1",
			isDirectory: false,
			revision: 10,
			createRevision: 3,
			modRevision: 10,
		},
		{
			key: "service-account-2",
			isDirectory: false,
			revision: 8,
			createRevision: 4,
			modRevision: 8,
		},
	],
	"jobs/": [
		{
			key: "cleanup-old-data",
			isDirectory: false,
			revision: 300,
			createRevision: 100,
			modRevision: 300,
		},
		{
			key: "sync-inventory",
			isDirectory: false,
			revision: 250,
			createRevision: 101,
			modRevision: 250,
		},
		{
			key: "generate-reports",
			isDirectory: false,
			revision: 180,
			createRevision: 102,
			modRevision: 180,
		},
		{
			key: "backup-database",
			isDirectory: false,
			revision: 400,
			createRevision: 103,
			modRevision: 400,
		},
		{
			key: "send-notifications",
			isDirectory: false,
			revision: 150,
			createRevision: 104,
			modRevision: 150,
		},
	],
	"locks/": [
		{
			key: "deployment-lock",
			isDirectory: false,
			revision: 890,
			createRevision: 200,
			modRevision: 890,
		},
		{
			key: "migration-lock",
			isDirectory: false,
			revision: 450,
			createRevision: 201,
			modRevision: 450,
		},
		{
			key: "cache-refresh",
			isDirectory: false,
			revision: 320,
			createRevision: 202,
			modRevision: 320,
		},
	],
	"elections/": [
		{
			key: "leader-api",
			isDirectory: false,
			revision: 1000,
			createRevision: 300,
			modRevision: 1000,
		},
		{
			key: "leader-worker",
			isDirectory: false,
			revision: 950,
			createRevision: 301,
			modRevision: 950,
		},
		{
			key: "leader-scheduler",
			isDirectory: false,
			revision: 920,
			createRevision: 302,
			modRevision: 920,
		},
	],
	"discovery/": [
		{
			key: "api-gateway-1",
			isDirectory: false,
			revision: 600,
			createRevision: 400,
			modRevision: 600,
		},
		{
			key: "api-gateway-2",
			isDirectory: false,
			revision: 598,
			createRevision: 401,
			modRevision: 598,
		},
		{
			key: "worker-1",
			isDirectory: false,
			revision: 550,
			createRevision: 402,
			modRevision: 550,
		},
		{
			key: "worker-2",
			isDirectory: false,
			revision: 548,
			createRevision: 403,
			modRevision: 548,
		},
		{
			key: "worker-3",
			isDirectory: false,
			revision: 545,
			createRevision: 404,
			modRevision: 545,
		},
		{
			key: "scheduler-1",
			isDirectory: false,
			revision: 500,
			createRevision: 405,
			modRevision: 500,
		},
	],
};

export const mockKeyValues: Record<string, string> = {
	leader: "8e9e05c52164694d",
	"cluster-id": "cdf818194e3a8c32",
	version: "3.5.12",
	"config/database": JSON.stringify(
		{
			host: "postgres.example.com",
			port: 5432,
			database: "production",
			max_connections: 100,
		},
		null,
		2,
	),
	"config/redis": JSON.stringify(
		{
			host: "redis.example.com",
			port: 6379,
			cluster_mode: true,
		},
		null,
		2,
	),
	"config/kafka": JSON.stringify(
		{
			brokers: ["kafka-1:9092", "kafka-2:9092", "kafka-3:9092"],
			consumer_group: "main-app",
			auto_offset_reset: "latest",
		},
		null,
		2,
	),
	"config/app/settings": JSON.stringify(
		{
			debug: false,
			log_level: "info",
			timezone: "UTC",
		},
		null,
		2,
	),
	"services/api-gateway": JSON.stringify(
		{
			endpoints: ["10.0.0.1:8080", "10.0.0.2:8080"],
			health_check: "/health",
			timeout_ms: 5000,
		},
		null,
		2,
	),
	"services/auth-service": JSON.stringify(
		{
			endpoints: ["10.0.0.10:8081"],
			jwt_expiry: 3600,
			refresh_enabled: true,
		},
		null,
		2,
	),
	"clusters/prod/node1": JSON.stringify(
		{
			ip: "10.0.1.1",
			status: "healthy",
			last_heartbeat: "2024-01-15T10:30:00Z",
		},
		null,
		2,
	),
	"jobs/cleanup-old-data": JSON.stringify(
		{
			schedule: "0 2 * * *",
			retention_days: 30,
			last_run: "2024-01-15T02:00:00Z",
		},
		null,
		2,
	),
	"locks/deployment-lock": JSON.stringify(
		{
			owner: "ci-runner-42",
			acquired_at: "2024-01-15T10:25:00Z",
			ttl: 300,
		},
		null,
		2,
	),
	"elections/leader-api": JSON.stringify(
		{
			leader_id: "api-gateway-1",
			term: 15,
			elected_at: "2024-01-15T00:00:00Z",
		},
		null,
		2,
	),
	"discovery/api-gateway-1": JSON.stringify(
		{
			address: "10.0.2.1:8080",
			health: "healthy",
			weight: 100,
			metadata: { version: "2.1.0", region: "us-east-1" },
		},
		null,
		2,
	),
};

export const mockClusterInfo: EtcdClusterInfo = {
	version: "3.5.12",
	clusterName: "etcd-cluster",
	endpoints: ["https://127.0.0.1:2379"],
	leader: "8e9e05c52164694d",
	revision: 1250,
	raftTerm: 4,
};

export const mockAuthStatus: EtcdAuthStatus = {
	enabled: true,
};

export const mockUsers: EtcdUser[] = [
	{ name: "root", roles: ["root"] },
	{ name: "admin", roles: ["root", "readwrite"] },
	{ name: "developer", roles: ["readwrite"] },
	{ name: "readonly-user", roles: ["readonly"] },
	{ name: "service-account", roles: ["readwrite"] },
];

export const mockRoles: EtcdRole[] = [
	{ name: "root", permissions: [] },
	{
		name: "readwrite",
		permissions: [{ permType: "readwrite", key: "/", prefix: true }],
	},
	{
		name: "readonly",
		permissions: [{ permType: "read", key: "/", prefix: true }],
	},
	{
		name: "config-admin",
		permissions: [{ permType: "readwrite", key: "config/", prefix: true }],
	},
	{
		name: "services-readonly",
		permissions: [{ permType: "read", key: "services/", prefix: true }],
	},
];

export const mockLeases: EtcdLease[] = [
	{
		id: "694d7d4c0c6c1e0a",
		ttl: 290,
		grantedTtl: 300,
		keys: ["services/api-gateway"],
	},
	{
		id: "694d7d4c0c6c1e0b",
		ttl: 3550,
		grantedTtl: 3600,
		keys: ["clusters/prod/node1", "clusters/prod/node2"],
	},
	{ id: "694d7d4c0c6c1e0c", ttl: 58, grantedTtl: 60, keys: [] },
];

export const mockAlarms: EtcdAlarm[] = [
	{ memberID: "8e9e05c52164694d", alarm: "NOSPACE" },
	{ memberID: "91bc3c398fb3c146", alarm: "CORRUPT" },
];

export const mockMembers: EtcdMember[] = [
	{
		id: "8e9e05c52164694d",
		name: "etcd-node-1",
		peerURLs: ["https://10.0.1.1:2380"],
		clientURLs: ["https://10.0.1.1:2379"],
		isLearner: false,
	},
	{
		id: "91bc3c398fb3c146",
		name: "etcd-node-2",
		peerURLs: ["https://10.0.1.2:2380"],
		clientURLs: ["https://10.0.1.2:2379"],
		isLearner: false,
	},
	{
		id: "f93e8e9b30c9f48a",
		name: "etcd-node-3",
		peerURLs: ["https://10.0.1.3:2380"],
		clientURLs: ["https://10.0.1.3:2379"],
		isLearner: false,
	},
];

export const mockEndpointHealth: EtcdEndpointHealth[] = [
	{ endpoint: "https://10.0.1.1:2379", health: true, took: "7.682µs" },
	{ endpoint: "https://10.0.1.2:2379", health: true, took: "8.234µs" },
	{ endpoint: "https://10.0.1.3:2379", health: true, took: "9.102µs" },
];

export const mockEndpointStatus: EtcdEndpointStatus[] = [
	{
		endpoint: "https://10.0.1.1:2379",
		dbSize: 25600000,
		dbSizeInUse: 20480000,
		leader: "8e9e05c52164694d",
		raftIndex: 15420,
		raftTerm: 4,
		raftAppliedIndex: 15420,
		version: "3.5.12",
	},
	{
		endpoint: "https://10.0.1.2:2379",
		dbSize: 25600000,
		dbSizeInUse: 20480000,
		leader: "8e9e05c52164694d",
		raftIndex: 15419,
		raftTerm: 4,
		raftAppliedIndex: 15419,
		version: "3.5.12",
	},
	{
		endpoint: "https://10.0.1.3:2379",
		dbSize: 25600000,
		dbSizeInUse: 20480000,
		leader: "8e9e05c52164694d",
		raftIndex: 15418,
		raftTerm: 4,
		raftAppliedIndex: 15418,
		version: "3.5.12",
	},
];
