/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeasesRouteImport } from './routes/leases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KeysIndexRouteImport } from './routes/keys/index'
import { Route as KeysSplatRouteImport } from './routes/keys/$'
import { Route as ClusterMembersRouteImport } from './routes/cluster/members'
import { Route as ClusterEndpointsRouteImport } from './routes/cluster/endpoints'
import { Route as ClusterAlarmsRouteImport } from './routes/cluster/alarms'
import { Route as AuthUsersRouteImport } from './routes/auth/users'
import { Route as AuthRolesRouteImport } from './routes/auth/roles'

const LeasesRoute = LeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysIndexRoute = KeysIndexRouteImport.update({
  id: '/keys/',
  path: '/keys/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysSplatRoute = KeysSplatRouteImport.update({
  id: '/keys/$',
  path: '/keys/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterMembersRoute = ClusterMembersRouteImport.update({
  id: '/cluster/members',
  path: '/cluster/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterEndpointsRoute = ClusterEndpointsRouteImport.update({
  id: '/cluster/endpoints',
  path: '/cluster/endpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterAlarmsRoute = ClusterAlarmsRouteImport.update({
  id: '/cluster/alarms',
  path: '/cluster/alarms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: '/auth/users',
  path: '/auth/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRolesRoute = AuthRolesRouteImport.update({
  id: '/auth/roles',
  path: '/auth/roles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leases': typeof LeasesRoute
  '/auth/roles': typeof AuthRolesRoute
  '/auth/users': typeof AuthUsersRoute
  '/cluster/alarms': typeof ClusterAlarmsRoute
  '/cluster/endpoints': typeof ClusterEndpointsRoute
  '/cluster/members': typeof ClusterMembersRoute
  '/keys/$': typeof KeysSplatRoute
  '/keys/': typeof KeysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leases': typeof LeasesRoute
  '/auth/roles': typeof AuthRolesRoute
  '/auth/users': typeof AuthUsersRoute
  '/cluster/alarms': typeof ClusterAlarmsRoute
  '/cluster/endpoints': typeof ClusterEndpointsRoute
  '/cluster/members': typeof ClusterMembersRoute
  '/keys/$': typeof KeysSplatRoute
  '/keys': typeof KeysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leases': typeof LeasesRoute
  '/auth/roles': typeof AuthRolesRoute
  '/auth/users': typeof AuthUsersRoute
  '/cluster/alarms': typeof ClusterAlarmsRoute
  '/cluster/endpoints': typeof ClusterEndpointsRoute
  '/cluster/members': typeof ClusterMembersRoute
  '/keys/$': typeof KeysSplatRoute
  '/keys/': typeof KeysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leases'
    | '/auth/roles'
    | '/auth/users'
    | '/cluster/alarms'
    | '/cluster/endpoints'
    | '/cluster/members'
    | '/keys/$'
    | '/keys/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leases'
    | '/auth/roles'
    | '/auth/users'
    | '/cluster/alarms'
    | '/cluster/endpoints'
    | '/cluster/members'
    | '/keys/$'
    | '/keys'
  id:
    | '__root__'
    | '/'
    | '/leases'
    | '/auth/roles'
    | '/auth/users'
    | '/cluster/alarms'
    | '/cluster/endpoints'
    | '/cluster/members'
    | '/keys/$'
    | '/keys/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeasesRoute: typeof LeasesRoute
  AuthRolesRoute: typeof AuthRolesRoute
  AuthUsersRoute: typeof AuthUsersRoute
  ClusterAlarmsRoute: typeof ClusterAlarmsRoute
  ClusterEndpointsRoute: typeof ClusterEndpointsRoute
  ClusterMembersRoute: typeof ClusterMembersRoute
  KeysSplatRoute: typeof KeysSplatRoute
  KeysIndexRoute: typeof KeysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leases': {
      id: '/leases'
      path: '/leases'
      fullPath: '/leases'
      preLoaderRoute: typeof LeasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys/': {
      id: '/keys/'
      path: '/keys'
      fullPath: '/keys/'
      preLoaderRoute: typeof KeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys/$': {
      id: '/keys/$'
      path: '/keys/$'
      fullPath: '/keys/$'
      preLoaderRoute: typeof KeysSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster/members': {
      id: '/cluster/members'
      path: '/cluster/members'
      fullPath: '/cluster/members'
      preLoaderRoute: typeof ClusterMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster/endpoints': {
      id: '/cluster/endpoints'
      path: '/cluster/endpoints'
      fullPath: '/cluster/endpoints'
      preLoaderRoute: typeof ClusterEndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster/alarms': {
      id: '/cluster/alarms'
      path: '/cluster/alarms'
      fullPath: '/cluster/alarms'
      preLoaderRoute: typeof ClusterAlarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/users': {
      id: '/auth/users'
      path: '/auth/users'
      fullPath: '/auth/users'
      preLoaderRoute: typeof AuthUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/roles': {
      id: '/auth/roles'
      path: '/auth/roles'
      fullPath: '/auth/roles'
      preLoaderRoute: typeof AuthRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeasesRoute: LeasesRoute,
  AuthRolesRoute: AuthRolesRoute,
  AuthUsersRoute: AuthUsersRoute,
  ClusterAlarmsRoute: ClusterAlarmsRoute,
  ClusterEndpointsRoute: ClusterEndpointsRoute,
  ClusterMembersRoute: ClusterMembersRoute,
  KeysSplatRoute: KeysSplatRoute,
  KeysIndexRoute: KeysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
